version: "3.6"

services:
  tf28-opencv-main:
    build: .
    volumes:
      - .:/tf28-opencv-main
      - /local/directory:/container/mount
    working_dir: /tf28-opencv-main
    ports:
      - 8888:8888
    # Setting up your GPU from here
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
